bskinn/sphobjinv

src/sphobjinv/inventory.py, tests/test_api_good_nonlocal.py
=> Add request header to overcome server filters on Inventory(url=...) download attempts

src/sphobjinv/__main__.py, src/sphobjinv/cmdline.py, tests/test_cli.py
So that `python -m sphobjinv` works.
=> Enable __main__ CLI entry point

CHANGELOG.md, README.rst, conftest.py, doc/source/api_usage.rst, doc/source/conf.py, src/sphobjinv/fileops.py, src/sphobjinv/inventory.py, src/sphobjinv/version.py, tests/test_api_fail.py, tests/test_api_good.py, tox.ini
Required no real changes to the code; `Path` inputs may already have worked fine.
Added appropriate tests, and updated docs to reflect.
=> Add official Path support for file interactions

requirements-flake8.txt, src/sphobjinv/cmdline.py, src/sphobjinv/data.py, src/sphobjinv/inventory.py, tests/test_flake8_ext.py
Identifying and fixing string glitches left over after increasing the line length for black
=> Add f8-implicit-str-concat and fix lints

conftest.py, doc/source/cli/suggest.rst, src/sphobjinv/schema.py, tests/test_api_fail.py, tests/test_api_good.py
Less-worse way of dealing with the merge conflicts, probably.
Closes #157.
=> Manually apply changes from mutmut branch

doc/source/cli/convert.rst, doc/source/cli/suggest.rst, src/sphobjinv/cli/core.py, src/sphobjinv/cli/parser.py, tests/test_cli.py
=> Prohibit CLI use of -u and stdin inventory read

CHANGELOG.md
Helps to satisfy Tidelift release info requirements
Closes #161
=> Split CHANGELOG by prerelease

README.rst, requirements-ci.txt, requirements-dev.txt, requirements-rtd.txt, setup.py, tests/test_api_good.py, tox.ini
=> Freshen tox

.readthedocs.yml, CHANGELOG.md, azure-pipelines.yml, conftest.py, requirements-ci.txt, setup.py, src/sphobjinv/cli/core.py, src/sphobjinv/cli/load.py, src/sphobjinv/cli/parser.py, src/sphobjinv/cli/ui.py, src/sphobjinv/cli/write.py, src/sphobjinv/inventory.py, src/sphobjinv/re.py, tests/test_fixture.py, tests/test_readme.py
=> Complete f-string conversion.

CHANGELOG.md, azure-pipelines.yml, doc/source/conf.py, doc/source/levenshtein.rst, setup.py
Closes #172 and closes #173, once fully implemented.
=> Add more explicit support for python-Levenshtein

azure-pipelines.yml, requirements-flake8.txt, src/sphobjinv/cli/ui.py, tests/test_cli.py, tox.ini
=> Flake8 noqa

setup.py
Hopefully for to restore the dependents tab @ Github
=> Add name arg back to setup() call

doc/source/customfile.rst
Doc fix
- Fix to `sphobjinv` version number (generalize to 2.x from 2.0)
- Add missing paren in final `intersphinx_mapping` example
No
Minor typo fix, no docs/tests/CHANGELOG effect.
- ~Documentation~
- ~Tests~
- ~CHANGELOG~
=> Fix customfile.rst

.coveragerc, .github/workflows/ci_tests.yml, CHANGELOG.md, CONTRIBUTING.md, README.rst, azure-pipelines.yml, pyproject.toml, requirements-ci.txt, requirements-dev.txt, requirements-rtd.txt, setup.cfg, src/sphobjinv/_vendored/__init__.py, src/sphobjinv/_vendored/fuzzywuzzy/LICENSE.txt, src/sphobjinv/_vendored/fuzzywuzzy/__init__.py, src/sphobjinv/_vendored/fuzzywuzzy/benchmarks.py, src/sphobjinv/_vendored/fuzzywuzzy/fuzz.py, src/sphobjinv/_vendored/fuzzywuzzy/process.py, src/sphobjinv/_vendored/fuzzywuzzy/tests.py, src/sphobjinv/_vendored/fuzzywuzzy/utils.py, src/sphobjinv/inventory.py, src/sphobjinv/version.py, tests/test_api_good.py, tests/test_readme.py, tox.ini
Main portion of response to #211; docs still need to be updated.
=> Vendor fuzzywuzzy and update project infra

CHANGELOG.md, doc/source/conf.py, doc/source/index.rst, doc/source/levenshtein.rst, requirements-ci.txt, requirements-dev.txt, requirements-rtd.txt, src/sphobjinv/_vendored/fuzzywuzzy/__init__.py, src/sphobjinv/inventory.py
=> Add Levenshtein deprecation/removal update to docs

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml, requirements-flake8.txt, src/sphobjinv/version.py, tests/test_api_good.py, tests/test_fixture.py, tox.ini
Complete v2.2.2 release process
=> Merge release-2.2.2 back into main

CHANGELOG.md, README.rst, doc/source/conf.py, src/sphobjinv/cli/core.py, tests/test_cli.py
=> Better suggest messages surrounding results counts and current threshold value

CHANGELOG.md, README.rst, doc/source/cli/convert.rst, src/sphobjinv/cli/load.py, src/sphobjinv/cli/ui.py, tests/test_cli_nonlocal.py
=> Add more descriptive status information when retrieving a remote inventory

CHANGELOG.md, README.rst, doc/source/cli/suggest.rst, doc/source/index.rst, src/sphobjinv/cli/suggest.py
=> Add project & version print to suggest output

CONTENT_LICENSE.txt, LICENSE.txt, README.rst
Want Github to recognize the project as being MIT licensed.
=> Split code and content license
