README.rst, conftest.py, doc/source/api_usage.rst, doc/source/cli/convert.rst, doc/source/cli/suggest.rst
Also fix README URLs to shields.io and codecov.io, updating them to `master` from `dev`.
=> Fix Github URLs after branch reorganization

.travis.yml, src/sphobjinv/inventory.py, tox.ini
Also add tox env for sphobjinv import-time warnings -- these are not captured by pytest's machinery!
=> Adjust attr.s() invocation for cmp argument deprecation

.travis.yml, README.rst, doc/source/cli/convert.rst, doc/source/cli/index.rst, doc/source/conf.py, doc/source/customfile.rst, doc/source/index.rst, doc/source/syntax.rst, requirements-dev.txt, requirements-rtd.txt, requirements-travis.txt, src/sphobjinv/__init__.py, src/sphobjinv/cmdline.py, src/sphobjinv/data.py, src/sphobjinv/enum.py, src/sphobjinv/error.py, src/sphobjinv/fileops.py, src/sphobjinv/inventory.py, src/sphobjinv/re.py, src/sphobjinv/schema.py, src/sphobjinv/version.py, src/sphobjinv/zlib.py
- Switch certain CLI outputs in docs to `.. program-output::`, to avoid having to manually update things in the docs that have no API significance on every version change
- Add `linkcheck` task to CI and fix links
- Switch all regex patterns to use raw strings, for clarity
=> Miscellaneous docs tweaks; update regex patterns

requirements-dev.txt
Will enable builds with 'python -m pep517.build' instead of
'python setup.py'.
=> Add pep517 to req'ts-dev

CHANGELOG.md, requirements-ci.txt, requirements-dev.txt, src/sphobjinv/cli/core.py, tests/test_api_fail.py, tests/test_api_good.py, tests/test_cli.py, tests/test_fixture.py, tests/test_flake8_ext.py, tests/test_readme.py, tox.ini
Cosmetic fix, but it was bugging me.
Closes #144 and #125 (had to switch away from `pytest-subtests`, at least for now, due to major compatibility problems (probably) with recent `pytest`).
=> Remove extra newline before suggest tables

doc/source/index.rst
All added to `index.rst`.
Closes #128 and closes #129.
=> Add PyOhio 2019 talk and POSIX packages

doc/source/conf.py, src/sphobjinv/fileops.py, tests/test_cli.py, tests/test_readme.py
Where feasible, now using `.read_text()` and related methods.
Couple of spots that had to use explicit file handles, though.
Closes #167
=> Refactor file interactions to Paths

doc/source/levenshtein.rst
It used to say `avaialble`, but that should be `available`.
=> Fix typo in doc/source/levenshtein.rst

CHANGELOG.md, src/sphobjinv/data.py, src/sphobjinv/inventory.py, tests/test_api_good.py
Lint fix
- Removes some unnecessary `pass` statements and explicit inheritance from `object`
- Some internal `type(...) is ...` checks were replaced with `isinstance(...)`
No.
- ~Documentation~
- ~Tests~
=> Fix new flake8-pie lints

tests/test_api_good.py
Setting the groundwork for the test suite and CI to work cleanly with #226.
The `pytest.xfail` for the `fonttools` case in the new '--testall suggest' test should trigger with the fix in #226.
=> Add test case info for `objects_fonttools.inv` and add --testall suggestion functionality test

CHANGELOG.md, src/sphobjinv/_vendored/fuzzywuzzy/utils.py, tests/test_api_good.py
Reduces (removes?) the risk of getting UnicodeDecodeErrors. Unknown consequences for the actual search functionality...
This may not be the correct way to actually solve it, but it does remove the error and makes suggest work on the objects.inv in question.
Not sure if I should have added a test (the only way I could think of was a smoke test for that particular URL, which I thought didn't really make sense, as it will require a download and the issue may go away from there).
I hope the CHANGELOG entry is close to acceptable.
Closes #225 
- Documentation *(Ed: Not needed)*
=> Fix(Ignore) UnicodeDecodeError

.pre-commit-config.yaml, CHANGELOG.md, azure-pipelines.yml, conftest.py, src/sphobjinv/cli/core.py, tests/test_cli.py
=> Fix no subparser

CHANGELOG.md, setup.cfg, setup.py
The old `license_file` setup.cfg field is deprecated, with the
list-based license_files now preferred. Fixed.
Improved the retrieval of `__version__` from within the package
by using an intermediary namespace dict with `exec()`, and recovering
the retrieved value from that.
- x Documentation
- x Tests
=> Setup: Modernize to license_files and improve __version__

azure-pipelines.yml, conftest.py, src/sphobjinv/cli/load.py, tests/test_readme.py, tox.ini
With this PR, they're no longer run as part of the core test suite; only as part of the Azure Pipelines auxiliary CI.
This will help ease the pain of #260, and also will minimize the thrashing of the commit history during general development... README glitches will only be surfaced on PR merge and releases.
Closes #260.
=> Compartmentalize README doc/shell tests

.pre-commit-config.yaml, CHANGELOG.md, README.rst, src/sphobjinv/cli/suggest.py
- Re-order the up-front output for CLI suggest
- Add dividers to CLI suggest up-front output for easier readability
- Relocate internal `sys.exit()` for reduced surprise
=> Modify CLI suggest output and mechanics

.github/workflows/ci_tests.yml, CHANGELOG.md, azure-pipelines.yml, requirements-ci.txt, requirements-dev.txt, requirements-flake8.txt, setup.cfg, tests/test_api_good.py, tests/test_cli.py, tests/test_fixture.py, tests/test_flake8_ext.py, tests/test_readme.py, tox.ini
Resolves #265.
Fix was as recommended by @okken in https://github.com/bskinn/sphobjinv/issues/264#issuecomment-1324030814
=> Update pytest-check pin and `check` usage

.gitattributes, CHANGELOG.md, MANIFEST.in, azure-coretest.yml, azure-pipelines.yml, azure-sdisttest.yml, conftest.py, doc/source/index.rst, src/sphobjinv/version.py, tests/test_fixture.py
Resolves #264.
Whole bunch of stuff to make an sdist actually testable needs to be packaged.
=> Update MANIFEST.in to enable a testable sdist

doc/source/index.rst, doc/source/syntax.rst
Docs change.
I simply add a mention of what Sphinx expects for priorities other than 1 and -1.
Just reading the current docs led to me think 0 would be low priority, and then 2, 3, 4, etc. higher priorities.
I'm not sure if priorities higher than 2 make sense to Sphinx :confused: 
No.
=> Mention priority 0 and 2

CHANGELOG.md, doc/source/_templates/footer.html
Fix
The `super` keyword used in a statement in the HTML footer template was missing parentheses to perform a method call; this caused the template rendering to emit a Python string describing the parent template object, instead of rendering the parent template as intended.
Closes #298.
=> Fixup: add missing call operator in template

CHANGELOG.md, doc/source/conf.py, requirements-ci.txt, requirements-dev.txt, requirements-rtd.txt
- `sphinx-ordering` is no longer used in the test suite, and is starting to fall out of compatibility in some environments
- `sphinx-removed-in` is obsolete since Sphinx 7.3
=> Trim project dependencies

CHANGELOG.md, tests/test_valid_objects.py, tox.ini
This PR will (hopefully) make the tests pass with Sphinx 8.2.
See #314 for the related discussion.
=> Skip more characters in test_name_lead_chars for Sphinx 8.2
